### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by Kirb7890** [HelloOO7/BounceTales#5]
so i saw your reddit comment and i have a question
do you still have the multiplayer version of bounce tales you made? (just asking)
if you do, can you please share it? thanks!

**Comment by HelloOO7** [comment]
I do not have it anymore, but it was pretty much just binding one set of controls (numpad) to a different BounceObject than the other (arrow keys).

Making an actual multiplayer mod would be out of scope of this repository since it would require significant changes to how a lot of the game logic and physics works.

**Comment by SuperPou1** [comment]
i'm trying to replicate what you did but i can't spawn a second bounceobj that can be controlled seperately. can you give a hint?

**Comment by HelloOO7** [comment]
I think you have to hook to where the main BounceObject (for the player) is created, clone it, make its ID unique and then add it to the scene, but there's probably a bit more to be changed if you actually want it to be controllable. I'd give you the source code if I could but I don't have it anymore (I used the same directory for experiments and the decomp before I made it public, and once I did I cleaned up these changes to keep the behavior the same as in the original game).

Anyhow, it was just a small experiment, and it wouldn't be trivial to actually make the game fully playable like that.

**Comment by HelloOO7** [comment]
It's really weird though, I could almost swear I had a separate Git branch with the local MP changes, but it's nowhere here. Maybe I force-pushed the repo without the branch at some point and it disappeared...

**Comment by SuperPou1** [comment]
well, i tried to make a second player that makes the second bounceobject, added it to levelkey and a chapter, but it caused the game to crash every time even if the chapter wasn't modified

**Comment by HelloOO7** [comment]
Then you most likely misunderstood something about how the game/levels work. It's not exactly most straightforward job in the world. Patience and knowledge is key - if you just skimmed through the sources once, skim 10 more times and learn to understand it. Noone mastered Unreal Engine in a day either.

I can't seem to find a local MP branch in any of the Git repos I have locally either so that's the end of the line for me.
