### ISSUE TITLE
another question

### ISSUE THREAD

**Issue by Kirb7890** [HelloOO7/BounceTales#8]
are bumper and stalker actual unused enemies? just asking

**Comment by HelloOO7** [comment]
The names, I made up, but yes.

**Comment by Kirb7890** [comment]
it looks like it wouldve been chapter 9-11 enemies
bumper like a semicircle with springs
stalker like a ghost

**Comment by HelloOO7** [comment]
I only chose the names based on the behavior when spawned in. Bumper just drops an egg on contact with Bumpy Cracks. The stalker actually reminds me a lot of the Hypnotoids' behavior in Boing Voyage, but since I couldn't confirm whether it could actually be an unused Hypnotoid enemy, I named it stalker because of how it charges at you from everywhere. Neither of the enemies can be killed Mario-style.

**Comment by Kirb7890** [comment]
this made me think


there was going to be an alternate battle???

**Comment by HelloOO7** [comment]
Guess we'll never know. Can this be closed?
